### ISSUE TITLE
用 docker 启动失败

### ISSUE THREAD

**Issue by skrik2** [quzhi1/ChineseHistoricalSource#13]
根据 FATAL  Error: [config validation of [server].host]: value must be a valid hostname (see RFC 1123). 报错，改了 server.host 报错更多了

```
docker-compose up
Starting chinesehistoricalsource-master_elasticsearch_1 ... done
Starting chinesehistoricalsource-master_kibana_1        ... done
Attaching to chinesehistoricalsource-master_elasticsearch_1, chinesehistoricalsource-master_kibana_1
kibana_1         | [2023-03-29T07:47:05.684+00:00][FATAL][root] Error: [config validation of [server].host]: value must be a valid hostname (see RFC 1123).
kibana_1         |     at ObjectType.validate (/usr/share/kibana/node_modules/@kbn/config-schema/target_node/src/types/type.js:84:13)
kibana_1         |     at ConfigService.validateAtPath (/usr/share/kibana/node_modules/@kbn/config/target_node/src/config_service.js:198:19)
kibana_1         |     at /usr/share/kibana/node_modules/@kbn/config/target_node/src/config_service.js:205:169
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:37
kibana_1         |     at OperatorSubscriber._this._next (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
kibana_1         |     at OperatorSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/distinctUntilChanged.js:18:28
kibana_1         |     at OperatorSubscriber._this._next (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
kibana_1         |     at OperatorSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/map.js:10:24
kibana_1         |     at OperatorSubscriber._this._next (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/OperatorSubscriber.js:33:21)
kibana_1         |     at OperatorSubscriber.Subscriber.next (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subscriber.js:51:18)
kibana_1         |     at ReplaySubject._subscribe (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/ReplaySubject.js:54:24)
kibana_1         |     at ReplaySubject.Observable._trySubscribe (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:41:25)
kibana_1         |     at ReplaySubject.Subject._trySubscribe (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Subject.js:123:47)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:35:31
kibana_1         |     at Object.errorContext (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
kibana_1         |     at ReplaySubject.Observable.subscribe (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/share.js:66:18
kibana_1         |     at OperatorSubscriber.<anonymous> (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/lift.js:14:28)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:30:30
kibana_1         |     at Object.errorContext (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
kibana_1         |     at Observable.subscribe (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/map.js:9:16
kibana_1         |     at OperatorSubscriber.<anonymous> (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/lift.js:14:28)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:30:30
kibana_1         |     at Object.errorContext (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
kibana_1         |     at Observable.subscribe (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/distinctUntilChanged.js:13:16
kibana_1         |     at OperatorSubscriber.<anonymous> (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/lift.js:14:28)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:30:30
kibana_1         |     at Object.errorContext (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
kibana_1         |     at Observable.subscribe (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/operators/map.js:9:16
kibana_1         |     at SafeSubscriber.<anonymous> (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/lift.js:14:28)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:30:30
kibana_1         |     at Object.errorContext (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/util/errorContext.js:22:9)
kibana_1         |     at Observable.subscribe (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/Observable.js:26:24)
kibana_1         |     at /usr/share/kibana/node_modules/rxjs/dist/cjs/internal/firstValueFrom.js:24:16
kibana_1         |     at new Promise (<anonymous>)
kibana_1         |     at firstValueFrom (/usr/share/kibana/node_modules/rxjs/dist/cjs/internal/firstValueFrom.js:8:12)
kibana_1         |     at EnvironmentService.preboot (/usr/share/kibana/node_modules/@kbn/core-environment-server-internal/target_node/src/environment_service.js:40:169)
kibana_1         |     at Server.preboot (/usr/share/kibana/node_modules/@kbn/core-root-server-internal/target_node/src/server.js:132:55)
kibana_1         |     at Root.preboot (/usr/share/kibana/node_modules/@kbn/core-root-server-internal/target_node/src/root/index.js:45:32)
kibana_1         |     at processTicksAndRejections (node:internal/process/task_queues:96:5)
kibana_1         |     at bootstrap (/usr/share/kibana/node_modules/@kbn/core-root-server-internal/target_node/src/bootstrap.js:85:9)
kibana_1         |     at Command.<anonymous> (/usr/share/kibana/src/cli/serve/serve.js:180:5)
kibana_1         | 
kibana_1         |  FATAL  Error: [config validation of [server].host]: value must be a valid hostname (see RFC 1123).
kibana_1         | 
chinesehistoricalsource-master_kibana_1 exited with code 1
elasticsearch_1  | {"@timestamp":"2023-03-29T07:47:10.520Z", "log.level": "INFO", "message":"version[8.6.1], pid[65], build[docker/180c9830da956993e59e2cd70eb32b5e383ea42c/2023-01-24T21:35:11.506992272Z], OS[Linux/5.4.0-70-generic/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/19.0.1/19.0.1+10-21]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"13ccb6e6f2bf","elasticsearch.cluster.name":"elasticsearch-history-source"}
elasticsearch_1  | {"@timestamp":"2023-03-29T07:47:10.533Z", "log.level": "INFO", "message":"JVM home [/usr/share/elasticsearch/jdk], using bundled JDK [true]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"13ccb6e6f2bf","elasticsearch.cluster.name":"elasticsearch-history-source"}
elasticsearch_1  | {"@timestamp":"2023-03-29T07:47:10.534Z", "log.level": "INFO", "message":"JVM arguments [-Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -Djava.security.manager=allow, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j2.formatMsgNoLookups=true, -Djava.locale.providers=SPI,COMPAT, --add-opens=java.base/java.io=ALL-UNNAMED, -Des.cgroups.hierarchy.override=/, -XX:+UseG1GC, -Djava.io.tmpdir=/tmp/elasticsearch-12233290869648847447, -XX:+HeapDumpOnOutOfMemoryError, -XX:+ExitOnOutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -Xlog:gc*,gc+age=trace,safepoint:file=logs/gc.log:utctime,pid,tags:filecount=32,filesize=64m, -Xms500m, -Xmx500m, -XX:MaxDirectMemorySize=262144000, -XX:G1HeapRegionSize=4m, -XX:InitiatingHeapOccupancyPercent=30, -XX:G1ReservePercent=15, -Des.distribution.type=docker, --module-path=/usr/share/elasticsearch/lib, --add-modules=jdk.net, -Djdk.module.main=org.elasticsearch.server]", "ecs.version": "1.2.0","service.name":"ES_ECS","event.dataset":"elasticsearch.server","process.thread.name":"main","log.logger":"org.elasticsearch.node.Node","elasticsearch.node.name":"13ccb6e6f2bf","elasticsearch.cluster.name":"elasticsearch-history-source"}
^CGracefully stopping... (press Ctrl+C again to force)
Stopping chinesehistoricalsource-master_elasticsearch_1 ... done

```

环境

云服务器 Ubuntu20.04

```
root@6lnsbbetgsgcnijq:~# neofetch
            .-/+oossssoo+/-.               root@6lnsbbetgsgcnijq 
        `:+ssssssssssssssssss+:`           --------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 20.04.2 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Host: OpenStack Nova 13.2.1-20220808115737_bd245dd 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Kernel: 5.4.0-70-generic 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Uptime: 19 mins 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Packages: 670 (dpkg) 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Shell: bash 5.0.17 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Resolution: 1024x768 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   CPU: Intel Xeon Gold 6161 (1) @ 2.200GHz 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   GPU: 00:02.0 Cirrus Logic GD 5446 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Memory: 190MiB / 1987MiB 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/                          
  +sssssssssdmydMMMMMMMMddddyssssssss+                           
   /ssssssssssshdmNNNNmyNMMMMhssssss/
    .ossssssssssssssssssdMMMNysssso.
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`
            .-/+oossssoo+/-.


root@6lnsbbetgsgcnijq:~# docker version
Client: Docker Engine - Community
 Version:           23.0.2
 API version:       1.42
 Go version:        go1.19.7
 Git commit:        569dd73
 Built:             Mon Mar 27 16:16:18 2023
 OS/Arch:           linux/amd64
 Context:           default

Server: Docker Engine - Community
 Engine:
  Version:          23.0.2
  API version:      1.42 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       219f21b
  Built:            Mon Mar 27 16:16:18 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.19
  GitCommit:        1e1ea6e986c6c86565bc33d52e34b81b3e2bc71f
 runc:
  Version:          1.1.4
  GitCommit:        v1.1.4-0-g5fd4c4d
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0


root@6lnsbbetgsgcnijq:~# docker-compose -v
docker-compose version 1.25.0, build unknown

root@6lnsbbetgsgcnijq:~# ruby -v
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux-gnu]
```

**Comment by quzhi1** [comment]
ElasticSearch最新版本最近出了一些问题。我现在在尝试用OpenSearch重新写一遍。
